import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { App } from '../App'
let root:Root,container:HTMLDivElement,time:number
beforeEach(()=>{
  time=0;vi.spyOn(performance,'now').mockImplementation(()=>time)
  vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true)
  vi.stubGlobal('ResizeObserver',class {observe(){} disconnect(){}})
  vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn())
  vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockReturnValue({left:100,top:100,right:300,bottom:300,width:200,height:200,x:100,y:100,toJSON:()=>({})})
  vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(null)
  window.history.replaceState({},'', '/?fakeVision=1')
  container=document.createElement('div');document.body.appendChild(container);root=createRoot(container)
})
afterEach(()=>{act(()=>root.unmount());container.remove();vi.restoreAllMocks();vi.unstubAllGlobals();window.history.replaceState({},'','/')})
function click(label:string,at:number) {
  time=at
  const button=[...container.querySelectorAll('button')].find(button=>button.textContent===label)
  if(!button) throw new Error(`Missing button: ${label}`)
  act(()=>button.click())
}
it('drives the rendered application through the shared fake semantic pipeline',()=>{
  act(()=>root.render(<App/>))
  expect(container.querySelector('header code')?.textContent).toBe('CAMERA_PERMISSION')
  click('Camera ready',0);click('Hand found',10);click('Move cursor to target',400)
  expect(container.textContent).toContain('Шаг 2/5')
  click('Move cursor to target',450);expect(container.textContent).toContain('Шаг 3/5')
  click('Pinch / select',500);expect(container.textContent).toContain('Шаг 4/5')
  click('Fist hold',1200);expect(container.textContent).toContain('Шаг 5/5')
  click('Thumb Up hold',2000);expect(container.querySelector('header code')?.textContent).toBe('MENU')
  click('Thumb Up hold',2100);expect(container.querySelector('header code')?.textContent).toBe('MENU')
  expect(container.textContent).toContain('Сначала выбери тренировку щипком')
  click('Move cursor to target',2200);click('Pinch / select',2300)
  expect(container.querySelector('[data-gesture-target="bodyweight-squat"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(container.querySelector('header code')?.textContent).toBe('MENU')
  click('Thumb Up hold',3000);expect(container.querySelector('header code')?.textContent).toBe('CALIBRATION')
  click('Fist hold',4000);expect(container.querySelector('header code')?.textContent).toBe('MENU')
  click('Fist hold',5000);expect(container.querySelector('header code')?.textContent).toBe('TUTORIAL')
  click('Move cursor to target',5400);expect(container.textContent).toContain('Шаг 2/5')
  click('Camera error',6000);expect(container.querySelector('[role="alert"]')?.textContent).toContain('Камера отключена')
  click('Повторить / Retry',6100);expect(container.querySelector('header code')?.textContent).toBe('TUTORIAL')
})
it('hides fake controls by default and does not request camera before the start action',()=>{
  window.history.replaceState({},'','/')
  const getUserMedia=vi.fn()
  Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia},configurable:true})
  act(()=>root.render(<App/>))
  expect(container.textContent).not.toContain('Fake vision')
  expect(container.textContent).toContain('Включить камеру')
  expect(getUserMedia).not.toHaveBeenCalled()
})
it('renders a five-cycle pose workout, pause recovery, specific corrections and results',()=>{
 act(()=>root.render(<App/>));click('Camera ready',0)
 click('Продолжить без проверки жестов',500)
 click('Bodyweight SquatДемонстрационный подход · 5 повторений',1000)
 click('Подтвердить выбор',1500)
 click('Wrong camera angle',2000);expect(container.textContent).toContain('Повернись боком к камере')
 click('Stable calibration / countdown',7000);expect(container.querySelector('header code')?.textContent).toBe('COUNTDOWN')
 click('Pose tracking lost',12000);expect(container.querySelector('header code')?.textContent).toBe('CALIBRATION')
 click('Stable calibration / countdown',15000);click('Stable calibration / countdown',20000)
 expect(container.querySelector('header code')?.textContent).toBe('WORKOUT')
 click('Correct rep',26000);expect(container.textContent).toContain('1 / 5')
 click('Pose pause / resume',34000);expect(container.textContent).toContain('Тренировка на паузе')
 click('Pose pause / resume',40000);expect(container.querySelector('header code')?.textContent).toBe('WORKOUT')
 click('Shallow rep',46000);expect(container.textContent).toContain('Опустись немного ниже')
 click('Fast rep',54000);expect(container.textContent).toContain('Медленнее опускайся вниз')
 click('Incomplete extension',62000);expect(container.textContent).toContain('Заверши подъём')
 click('Correct rep',70000);expect(container.querySelector('header code')?.textContent).toBe('RESULTS')
 expect(container.textContent).toContain('Подход завершён');expect(container.textContent).toContain('40%')
 expect(container.textContent).toContain('Среднее время повторения')
 click('Повторить подход',78000);expect(container.querySelector('header code')?.textContent).toBe('CALIBRATION')
 click('Назад в меню',79000);expect(container.querySelector('header code')?.textContent).toBe('MENU')
})
