import type { SetCreate } from '../api/types';
/** Structural boundary for the A3 runner's compact set aggregates; no frames are persisted. */
export type MeasuredSet = { clientSetId: string; exerciseKey: string; specRevision: string | null; setIndex: number; targetReps: number; assessmentMode: 'camera' | 'manual'; status: 'completed' | 'partial'; totalReps: number; acceptedReps: number; durationMs: number; meanRepDurationMs: number | null; errorCounts: Record<string, number>; metrics: readonly { metrics: { minKneeAngle: number | null } }[]; targetSnapshot: { targetReps: number; restSeconds: number; planSets: number; durationSeconds: null } };
export function projectSessionSets(sets: readonly MeasuredSet[]): SetCreate[] {
  return sets.map(set => {
    const legacy = { depth_insufficient: set.errorCounts.depth_insufficient ?? 0, too_fast: set.errorCounts.too_fast ?? 0, incomplete_extension: set.errorCounts.incomplete_extension ?? 0 };
    const angles = set.metrics.map(rep => rep.metrics.minKneeAngle).filter((angle): angle is number => angle !== null);
    return { client_set_id: set.clientSetId, exercise_key: set.exerciseKey, set_index: set.setIndex, assessment_mode: set.assessmentMode, completion_status: set.status, spec_revision: set.specRevision, target_snapshot: { target_reps: set.targetSnapshot.targetReps, duration_seconds: set.targetSnapshot.durationSeconds, rest_seconds: set.targetSnapshot.restSeconds, plan_sets: set.targetSnapshot.planSets }, total_reps: set.totalReps, accepted_reps: set.assessmentMode === 'camera' ? set.acceptedReps : 0, duration_ms: Math.round(set.durationMs), error_counts: set.assessmentMode === 'manual' ? { depth_insufficient: 0, too_fast: 0, incomplete_extension: 0 } : legacy, generic_error_counts: set.assessmentMode === 'manual' ? {} : Object.fromEntries(Object.entries(set.errorCounts).filter(([code]) => !(code in legacy))), metrics: { mean_rep_duration_ms: set.meanRepDurationMs, mean_min_knee_angle: angles.length ? angles.reduce((sum, angle) => sum + angle, 0) / angles.length : null }, engine_version: set.assessmentMode === 'manual' ? 'manual-v1' : set.exerciseKey === 'bodyweight_squat' ? 'squat-v1' : 'generic-v1' };
  });
}
