"""create profiles and confirmed constraints

Revision ID: 6d76bd5ceb62
Revises: 298885d8eb24
Create Date: 2026-09-30 00:23:43.261898+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6d76bd5ceb62'
down_revision: str | None = '298885d8eb24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'health_constraints',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'code',
            postgresql.ENUM(
                'no_high_impact',
                'avoid_deep_knee_flexion',
                'avoid_overhead',
                name='health_constraints_code_enum',
            ),
            nullable=False,
        ),
        sa.Column(
            'source',
            postgresql.ENUM(
                'self_reported', 'document_extracted', name='health_constraints_source_enum'
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            postgresql.ENUM(
                'pending_confirmation',
                'confirmed',
                'rejected',
                name='health_constraints_status_enum',
            ),
            nullable=False,
        ),
        sa.Column('note', sa.String(length=500), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_health_constraints_user_id'), 'health_constraints', ['user_id'], unique=False
    )
    op.create_table(
        'profiles',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'goal',
            postgresql.ENUM(
                'general_fitness', 'strength_foundation', 'mobility', name='profiles_goal_enum'
            ),
            nullable=False,
        ),
        sa.Column(
            'experience_level',
            postgresql.ENUM(
                'beginner', 'intermediate', 'advanced', name='profiles_experience_enum'
            ),
            nullable=False,
        ),
        sa.Column('days_per_week', sa.SmallInteger(), nullable=False),
        sa.Column('session_minutes', sa.SmallInteger(), nullable=False),
        sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('locale', sa.String(length=35), nullable=False),
        sa.Column('timezone', sa.String(length=100), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name='ck_profiles_days'),
        sa.CheckConstraint('session_minutes BETWEEN 5 AND 120', name='ck_profiles_minutes'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
