"""Sprint 4B coach voice schedule jobs and guest recovery

Revision ID: 6d9526d00d1b
Revises: 041f28173bcc
Create Date: 2026-09-30 14:26:43.877639+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6d9526d00d1b'
down_revision: str | None = '041f28173bcc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'provider_budgets',
        sa.Column('scope', sa.Text(), nullable=False),
        sa.Column('day', sa.Date(), nullable=False),
        sa.Column('category', sa.Text(), nullable=False),
        sa.Column('used', sa.Integer(), nullable=False),
        sa.CheckConstraint('used >= 0', name='ck_provider_budget_positive'),
        sa.PrimaryKeyConstraint('scope', 'day', 'category'),
    )
    op.create_table(
        'calendar_connections',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tokens_encrypted', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'connected', 'revoked', 'error', name='calendar_connections_status_enum'
            ),
            server_default='connected',
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_table(
        'calendar_oauth_states',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('state_hash', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('state_hash'),
    )
    op.create_index(
        op.f('ix_calendar_oauth_states_user_id'),
        'calendar_oauth_states',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'calendar_sync_runs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('operation_id', sa.UUID(), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'operation_id', name='uq_calendar_sync_operation'),
    )
    op.create_index(
        op.f('ix_calendar_sync_runs_user_id'), 'calendar_sync_runs', ['user_id'], unique=False
    )
    op.create_table(
        'coach_conversations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_coach_conversations_user_id'),
        'coach_conversations',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'coach_preferences',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('voice_id', sa.Text(), nullable=True),
        sa.Column(
            'language',
            postgresql.ENUM('ru', 'kk', 'en', name='coach_preferences_language_enum'),
            nullable=False,
        ),
        sa.Column(
            'style',
            postgresql.ENUM(
                'calm',
                'supportive',
                'energetic',
                'strict',
                name='coach_preferences_style_enum',
            ),
            nullable=False,
        ),
        sa.Column('audio_enabled', sa.Boolean(), nullable=False),
        sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
        sa.CheckConstraint('revision >= 0', name='ck_coach_preferences_revision'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_table(
        'coach_proposals',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('operation_id', sa.UUID(), nullable=False),
        sa.Column(
            'kind',
            postgresql.ENUM(
                'schedule', 'plan_change', 'exercise_swap', name='coach_proposals_kind_enum'
            ),
            nullable=False,
        ),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('payload_hash', sa.Text(), nullable=False),
        sa.Column('source_revision', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'pending', 'confirmed', 'rejected', name='coach_proposals_status_enum'
            ),
            server_default='pending',
            nullable=False,
        ),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'operation_id', name='uq_coach_proposal_operation'),
    )
    op.create_index(
        op.f('ix_coach_proposals_user_id'), 'coach_proposals', ['user_id'], unique=False
    )
    op.create_table(
        'guest_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('secret_hash', sa.Text(), nullable=False),
        sa.Column('previous_hash', sa.Text(), nullable=True),
        sa.Column('previous_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('secret_hash'),
    )
    op.create_index(
        op.f('ix_guest_sessions_user_id'), 'guest_sessions', ['user_id'], unique=False
    )
    op.create_table(
        'schedule_preferences',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('timezone', sa.Text(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
        sa.CheckConstraint('duration_minutes BETWEEN 5 AND 120', name='ck_schedule_duration'),
        sa.CheckConstraint('revision >= 0', name='ck_schedule_revision'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_table(
        'ai_exercise_spec_revisions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('exercise_key', sa.Text(), nullable=False),
        sa.Column('movement_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ['exercise_key'],
            ['exercises.key'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_ai_exercise_spec_revisions_exercise_key'),
        'ai_exercise_spec_revisions',
        ['exercise_key'],
        unique=False,
    )
    op.create_index(
        op.f('ix_ai_exercise_spec_revisions_user_id'),
        'ai_exercise_spec_revisions',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'coach_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('conversation_id', sa.UUID(), nullable=False),
        sa.Column('operation_id', sa.UUID(), nullable=False),
        sa.Column('request_hash', sa.Text(), nullable=False),
        sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['coach_conversations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'operation_id', name='uq_coach_message_operation'),
    )
    op.create_index(
        op.f('ix_coach_messages_conversation_id'),
        'coach_messages',
        ['conversation_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_coach_messages_user_id'), 'coach_messages', ['user_id'], unique=False
    )
    op.create_table(
        'generation_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('operation_id', sa.UUID(), nullable=False),
        sa.Column(
            'execution_mode',
            postgresql.ENUM('live', 'fixture', name='generation_jobs_mode_enum'),
            nullable=False,
        ),
        sa.Column('input_revision', sa.Text(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'queued',
                'running',
                'completed',
                'fallback',
                'failed',
                'cancelled',
                'interrupted',
                name='generation_jobs_status_enum',
            ),
            server_default='queued',
            nullable=False,
        ),
        sa.Column('stage', sa.Text(), server_default='preparing_context', nullable=False),
        sa.Column('completed_specs', sa.Integer(), server_default='0', nullable=False),
        sa.Column('total_specs', sa.Integer(), server_default='0', nullable=False),
        sa.Column('result_plan_id', sa.UUID(), nullable=True),
        sa.Column('error_category', sa.Text(), nullable=True),
        sa.Column('lease_id', sa.UUID(), nullable=True),
        sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint('completed_specs BETWEEN 0 AND 16', name='ck_jobs_completed_specs'),
        sa.CheckConstraint('total_specs BETWEEN 0 AND 16', name='ck_jobs_total_specs'),
        sa.ForeignKeyConstraint(
            ['result_plan_id'], ['training_plans.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'operation_id', name='uq_generation_job_operation'),
    )
    op.create_index(
        op.f('ix_generation_jobs_result_plan_id'),
        'generation_jobs',
        ['result_plan_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False
    )
    op.create_table(
        'schedule_appointments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('plan_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'planned',
                'completed',
                'skipped',
                'cancelled',
                name='schedule_appointments_status_enum',
            ),
            server_default='planned',
            nullable=False,
        ),
        sa.Column(
            'sync_status',
            postgresql.ENUM(
                'local', 'pending', 'synced', 'error', name='schedule_appointments_sync_enum'
            ),
            server_default='local',
            nullable=False,
        ),
        sa.CheckConstraint('ends_at > starts_at', name='ck_schedule_time_order'),
        sa.CheckConstraint('length(title) BETWEEN 1 AND 120', name='ck_schedule_title'),
        sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_schedule_appointments_plan_id'),
        'schedule_appointments',
        ['plan_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_schedule_appointments_user_id'),
        'schedule_appointments',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'calendar_event_links',
        sa.Column('appointment_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('calendar_id', sa.Text(), server_default='primary', nullable=False),
        sa.Column('event_id', sa.Text(), nullable=False),
        sa.Column('etag', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['appointment_id'], ['schedule_appointments.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('appointment_id'),
    )
    op.create_index(
        op.f('ix_calendar_event_links_user_id'),
        'calendar_event_links',
        ['user_id'],
        unique=False,
    )
    op.add_column('ai_user_profiles', sa.Column('input_revision', sa.Text(), nullable=True))
    op.add_column(
        'ai_user_profiles',
        sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # Existing rows keep their exact declaration UUID as an immutable revision.
    revisions = sa.table(
        'ai_exercise_spec_revisions',
        sa.column('id'),
        sa.column('user_id'),
        sa.column('exercise_key'),
        sa.column('movement_spec'),
        sa.column('created_at'),
    )
    specs = sa.table(
        'ai_exercise_specs',
        sa.column('id'),
        sa.column('user_id'),
        sa.column('exercise_key'),
        sa.column('movement_spec'),
        sa.column('created_at'),
    )
    op.execute(
        revisions.insert().from_select(
            ['id', 'user_id', 'exercise_key', 'movement_spec', 'created_at'],
            sa.select(
                specs.c.id,
                specs.c.user_id,
                specs.c.exercise_key,
                specs.c.movement_spec,
                specs.c.created_at,
            ),
        )
    )
    postgresql.ENUM('camera', 'manual', name='workout_sets_assessment_enum').create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM('completed', 'partial', name='workout_sets_completion_enum').create(
        op.get_bind(), checkfirst=True
    )
    op.add_column(
        'workout_set_results',
        sa.Column(
            'assessment_mode',
            postgresql.ENUM('camera', 'manual', name='workout_sets_assessment_enum'),
            server_default='camera',
            nullable=False,
        ),
    )
    op.add_column(
        'workout_set_results',
        sa.Column(
            'completion_status',
            postgresql.ENUM('completed', 'partial', name='workout_sets_completion_enum'),
            server_default='completed',
            nullable=False,
        ),
    )
    op.add_column('workout_set_results', sa.Column('spec_revision', sa.UUID(), nullable=True))
    op.add_column(
        'workout_set_results',
        sa.Column('target_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_check_constraint(
        'ck_manual_no_accepted',
        'workout_set_results',
        sa.or_(sa.column('assessment_mode') != 'manual', sa.column('accepted_reps') == 0),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
