"""Persist per set engine identity for mixed workouts

Revision ID: ae1078bb4679
Revises: 6d9526d00d1b
Create Date: 2026-09-30 16:15:57.475721+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ae1078bb4679'
down_revision: str | None = '6d9526d00d1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_set_results', sa.Column('engine_version', sa.Text(), nullable=True))
    sets = sa.table(
        'workout_set_results', sa.column('session_id'), sa.column('engine_version')
    )
    sessions = sa.table(
        'workout_sessions', sa.column('id'), sa.column('client_engine_version')
    )
    legacy_version = (
        sa.select(sessions.c.client_engine_version)
        .where(sessions.c.id == sets.c.session_id)
        .scalar_subquery()
    )
    op.execute(sets.update().values(engine_version=legacy_version))
    op.alter_column(
        'workout_set_results', 'engine_version', existing_type=sa.Text(), nullable=False
    )
    op.create_check_constraint(
        'ck_set_engine_length',
        'workout_set_results',
        sa.func.length(sa.column('engine_version')).between(1, 50),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
