"""create exercise catalog and seed squat

Revision ID: c8a350ad1383
Revises: 6d76bd5ceb62
Create Date: 2026-09-30 00:25:33.360689+00:00
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c8a350ad1383'
down_revision: str | None = '6d76bd5ceb62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    catalog = op.create_table(
        'exercises',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('key', sa.String(length=80), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column(
            'difficulty',
            postgresql.ENUM(
                'beginner', 'intermediate', 'advanced', name='exercises_difficulty_enum'
            ),
            nullable=False,
        ),
        sa.Column('equipment_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'impact_level',
            postgresql.ENUM('low', 'medium', 'high', name='exercises_impact_enum'),
            nullable=False,
        ),
        sa.Column(
            'camera_angle',
            postgresql.ENUM('side', 'front', 'none', name='exercises_camera_angle_enum'),
            nullable=False,
        ),
        sa.Column(
            'contraindication_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('analysis_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', name='uq_exercises_key'),
    )
    seed_squat(op.get_bind(), catalog)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass


def seed_squat(connection, catalog):
    connection.execute(
        postgresql.insert(catalog)
        .values(
            id=uuid.UUID('1b4dd90c-e3e1-4c04-b392-c45da876a9c7'),
            key='bodyweight_squat',
            name='Bodyweight Squat',
            difficulty='beginner',
            equipment_codes=['none'],
            impact_level='low',
            camera_angle='side',
            contraindication_tags=['avoid_deep_knee_flexion'],
            analysis_profile={
                'version': 1,
                'engine_key': 'bodyweight_squat_side_v1',
                'engine_version': 'squat-v1',
                'target_reps': 5,
                'supported_client': 'web',
            },
            is_active=True,
        )
        .on_conflict_do_nothing(index_elements=[catalog.c.key])
    )
