"""create deterministic training plans

Revision ID: f8cbfe1577f4
Revises: c8a350ad1383
Create Date: 2026-09-30 00:27:23.206770+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f8cbfe1577f4'
down_revision: str | None = 'c8a350ad1383'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'training_plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'draft', 'active', 'completed', 'archived', name='training_plans_status_enum'
            ),
            nullable=False,
        ),
        sa.Column(
            'source',
            postgresql.ENUM('deterministic', 'ai_assisted', name='training_plans_source_enum'),
            nullable=False,
        ),
        sa.Column('starts_on', sa.Date(), nullable=False),
        sa.Column('rationale', sa.String(length=500), nullable=False),
        sa.Column('generator_version', sa.String(length=50), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False
    )
    op.create_index(
        'uq_training_plans_active_user',
        'training_plans',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        'training_plan_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('plan_id', sa.UUID(), nullable=False),
        sa.Column('exercise_id', sa.UUID(), nullable=False),
        sa.Column('day_index', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('sets', sa.Integer(), nullable=False),
        sa.Column('target_reps', sa.Integer(), nullable=False),
        sa.Column('rest_seconds', sa.Integer(), nullable=False),
        sa.Column('tempo_hint', sa.String(length=80), nullable=True),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('day_index BETWEEN 0 AND 6', name='ck_plan_items_day'),
        sa.CheckConstraint('position >= 0', name='ck_plan_items_position'),
        sa.CheckConstraint('rest_seconds BETWEEN 0 AND 600', name='ck_plan_items_rest'),
        sa.CheckConstraint('sets BETWEEN 1 AND 10', name='ck_plan_items_sets'),
        sa.CheckConstraint('target_reps BETWEEN 1 AND 100', name='ck_plan_items_reps'),
        sa.ForeignKeyConstraint(
            ['exercise_id'],
            ['exercises.id'],
        ),
        sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('plan_id', 'day_index', 'position', name='uq_plan_items_position'),
    )
    op.create_index(
        op.f('ix_training_plan_items_exercise_id'),
        'training_plan_items',
        ['exercise_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_training_plan_items_plan_id'),
        'training_plan_items',
        ['plan_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
