"""create workout sessions and aggregate results

Revision ID: e2dc2dbe10a5
Revises: f8cbfe1577f4
Create Date: 2026-09-30 00:29:42.489296+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e2dc2dbe10a5'
down_revision: str | None = 'f8cbfe1577f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workout_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_session_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('plan_id', sa.UUID(), nullable=True),
        sa.Column(
            'status',
            postgresql.ENUM(
                'started', 'completed', 'abandoned', name='workout_sessions_status_enum'
            ),
            server_default='started',
            nullable=False,
        ),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('client_engine_version', sa.String(length=50), nullable=False),
        sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status != 'completed' OR completed_at IS NOT NULL",
            name='ck_sessions_completed_at',
        ),
        sa.CheckConstraint(
            'completed_at IS NULL OR completed_at >= started_at', name='ck_sessions_time_order'
        ),
        sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'client_session_id', name='uq_workout_sessions_client'),
    )
    op.create_index(
        op.f('ix_workout_sessions_plan_id'), 'workout_sessions', ['plan_id'], unique=False
    )
    op.create_index(
        op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False
    )
    op.create_table(
        'workout_set_results',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_set_id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('exercise_id', sa.UUID(), nullable=False),
        sa.Column('set_index', sa.Integer(), nullable=False),
        sa.Column('total_reps', sa.Integer(), nullable=False),
        sa.Column('accepted_reps', sa.Integer(), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=False),
        sa.Column('error_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'accepted_reps <= total_reps', name='ck_set_results_accepted_total'
        ),
        sa.CheckConstraint('accepted_reps BETWEEN 0 AND 500', name='ck_set_results_accepted'),
        sa.CheckConstraint(
            'duration_ms BETWEEN 0 AND 3600000', name='ck_set_results_duration'
        ),
        sa.CheckConstraint('set_index >= 1', name='ck_set_results_index'),
        sa.CheckConstraint('total_reps BETWEEN 0 AND 500', name='ck_set_results_total'),
        sa.ForeignKeyConstraint(
            ['exercise_id'],
            ['exercises.id'],
        ),
        sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id', 'client_set_id', name='uq_set_results_client'),
        sa.UniqueConstraint('session_id', 'set_index', name='uq_set_results_index'),
    )
    op.create_index(
        op.f('ix_workout_set_results_exercise_id'),
        'workout_set_results',
        ['exercise_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_workout_set_results_session_id'),
        'workout_set_results',
        ['session_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
