"""Sprint 4A personalized coaching

Revision ID: 041f28173bcc
Revises: d14a8a94311f
Create Date: 2026-09-30 10:51:18.360882+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '041f28173bcc'
down_revision: str | None = 'd14a8a94311f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ai_plan_runs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('model', sa.Text(), nullable=False),
        sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'completed', 'fallback', 'failed', name='ai_plan_runs_status_enum'
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ai_plan_runs_user_id'), 'ai_plan_runs', ['user_id'], unique=False)
    op.create_table(
        'ai_user_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('model', sa.Text(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'completed', 'fallback', 'synthetic', name='ai_profiles_status_enum'
            ),
            nullable=False,
        ),
        sa.CheckConstraint('version >= 1', name='ck_ai_profiles_version'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'version', name='uq_ai_profile_version'),
    )
    op.create_index(
        op.f('ix_ai_user_profiles_user_id'), 'ai_user_profiles', ['user_id'], unique=False
    )
    op.create_table(
        'user_ai_context',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('self_description', sa.Text(), nullable=False),
        sa.Column(
            'preferred_coach_style',
            postgresql.ENUM(
                'calm', 'energetic', 'strict', 'supportive', name='ai_context_style_enum'
            ),
            nullable=False,
        ),
        sa.Column(
            'preferred_language',
            postgresql.ENUM('ru', 'kk', 'en', name='ai_context_language_enum'),
            nullable=False,
        ),
        sa.Column(
            'additional_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            'length(self_description) <= 5000', name='ck_ai_context_description_length'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_ai_context_user'),
    )
    op.create_index(
        op.f('ix_user_ai_context_user_id'), 'user_ai_context', ['user_id'], unique=False
    )
    op.create_table(
        'user_documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('filename', sa.Text(), nullable=False),
        sa.Column('media_type', sa.Text(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('extracted_text', sa.Text(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'uploaded', 'processed', 'failed', name='user_documents_status_enum'
            ),
            nullable=False,
        ),
        sa.Column('message', sa.Text(), nullable=True),
        sa.CheckConstraint('length(extracted_text) <= 50000', name='ck_documents_text_length'),
        sa.CheckConstraint(
            'length(filename) BETWEEN 1 AND 255', name='ck_documents_filename_length'
        ),
        sa.CheckConstraint('size_bytes BETWEEN 0 AND 5242880', name='ck_documents_size'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False
    )
    op.create_table(
        'ai_exercise_specs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('exercise_key', sa.Text(), nullable=False),
        sa.Column('display_name', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('difficulty', sa.Text(), nullable=False),
        sa.Column('equipment_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('camera_angle', sa.Text(), nullable=False),
        sa.Column('movement_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('generated_by_model', sa.Text(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'generated',
                'valid',
                'invalid',
                'manual_only',
                name='ai_exercise_specs_status_enum',
            ),
            nullable=False,
        ),
        sa.Column(
            'validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            'length(display_name) BETWEEN 1 AND 48', name='ck_ai_specs_name_length'
        ),
        sa.ForeignKeyConstraint(
            ['exercise_key'],
            ['exercises.key'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('exercise_key', name='uq_ai_exercise_specs_key'),
    )
    op.create_index(
        op.f('ix_ai_exercise_specs_user_id'), 'ai_exercise_specs', ['user_id'], unique=False
    )
    op.create_table(
        'document_chunks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint('chunk_index BETWEEN 0 AND 29', name='ck_document_chunks_index'),
        sa.CheckConstraint('length(content) <= 1800', name='ck_document_chunks_length'),
        sa.ForeignKeyConstraint(['document_id'], ['user_documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_index'),
    )
    op.create_index(
        op.f('ix_document_chunks_document_id'),
        'document_chunks',
        ['document_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False
    )
    op.create_table(
        'document_facts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('normalized_fact', sa.Text(), nullable=False),
        sa.Column('source_excerpt', sa.Text(), nullable=False),
        sa.Column('constraint_code', sa.Text(), nullable=True),
        sa.Column(
            'status',
            postgresql.ENUM(
                'pending', 'confirmed', 'rejected', name='document_facts_status_enum'
            ),
            nullable=False,
        ),
        sa.CheckConstraint('length(normalized_fact) <= 120', name='ck_document_facts_length'),
        sa.CheckConstraint(
            'length(source_excerpt) <= 240', name='ck_document_facts_excerpt_length'
        ),
        sa.ForeignKeyConstraint(['document_id'], ['user_documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_document_facts_document_id'), 'document_facts', ['document_id'], unique=False
    )
    op.create_index(
        op.f('ix_document_facts_user_id'), 'document_facts', ['user_id'], unique=False
    )
    op.add_column('exercises', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.create_index(
        op.f('ix_exercises_owner_user_id'), 'exercises', ['owner_user_id'], unique=False
    )
    op.create_foreign_key(
        None, 'exercises', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column(
        'training_plans',
        sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        'workout_set_results',
        sa.Column(
            'generic_error_counts',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
