import { useTranslation } from '../shared/uiLanguage'
import type { SetCreate } from '../api/types';
import { GestureTarget } from '../features/gesture-navigation/GestureTarget';
export function SessionResultsPage({ sets, mode, status, elapsedMs, names, syncMessage, onProgress, onPlan, onRetry }: { sets: readonly SetCreate[]; mode: 'full' | 'quick-demo'; status: 'in_progress' | 'completed' | 'stopped'; elapsedMs: number; names: Readonly<Record<string, string>>; syncMessage: string; onProgress: () => void; onPlan: () => void; onRetry: () => void }) {
  const { translateUi } = useTranslation()

  const assessed = sets.filter(set => set.assessment_mode === 'camera').reduce((sum, set) => sum + set.total_reps, 0), accepted = sets.reduce((sum, set) => sum + set.accepted_reps, 0), manual = sets.filter(set => set.assessment_mode === 'manual' && set.completion_status === 'completed').length;
  return <section className="session-results" data-guide-target="results"><p className="dm-label">{translateUi(mode === 'quick-demo' ? 'QUICK DEMO / ONE SET' : 'FULL WORKOUT / ACTUAL SETS')}</p><h1>{translateUi(status === 'stopped' ? 'Тренировка остановлена' : 'Тренировка завершена')}</h1><p>{translateUi("Подходов: ")}{sets.length}{translateUi(" · Отмечено вручную: ")}{manual}{translateUi(" · Время с отдыхом: ")}{Math.round(elapsedMs / 1000)}{translateUi(" с")}</p>
    <p>{translateUi("Камера оценила ")}{assessed}{translateUi(" повторений. Корректных: ")}{accepted}{translateUi("; с ошибками: ")}{assessed - accepted}. {translateUi(assessed ? `${Math.round(accepted / assessed * 100)}%` : 'Оценка камерой отсутствует')}.</p>
    {!sets.length && <p>{translateUi("Завершённых повторений нет. Пустая тренировка не отправляется в прогресс.")}</p>}
    <div className="session-set-list">{sets.map(set => <article className="dm-panel" key={set.client_set_id}><h3>{translateUi(names[set.exercise_key] ?? set.exercise_key.replace(/_/g, ' '))}{translateUi(" · подход ")}{set.set_index}</h3><p>{translateUi(set.assessment_mode === 'manual' ? 'Отмечено пользователем · камера не оценивала технику' : `Оценены камерой: ${set.total_reps} · корректные: ${set.accepted_reps}`)} · {translateUi(set.completion_status === 'partial' ? 'Неполный подход' : 'Завершён')}</p><p>{translateUi("Активное время: ")}{Math.round(set.duration_ms / 1000)}{translateUi(" с · Среднее время повторения: ")}{translateUi(set.metrics.mean_rep_duration_ms === null ? 'не измерено' : `${(set.metrics.mean_rep_duration_ms / 1000).toFixed(1)} с`)}</p>
      {Object.keys(set.generic_error_counts ?? {}).length > 0 && <p>{translateUi("Подсказки техники: ")}{translateUi(Object.entries(set.generic_error_counts ?? {}).map(([code, count]) => `${translateUi(code)}: ${count}`).join(' · '))}</p>}
    </article>)}</div><p role="status">{translateUi(syncMessage)}</p><div className="dm-actions"><GestureTarget id="results-progress" onSelect={onProgress}>{translateUi("Открыть прогресс")}</GestureTarget><GestureTarget id="results-plan" onSelect={onPlan}>{translateUi("Вернуться к плану")}</GestureTarget><GestureTarget id="results-sync" onSelect={onRetry}>{translateUi("Повторить сохранение")}</GestureTarget></div></section>;
}
