import type { SetCreate } from '../api/types';
import { GestureTarget } from '../features/gesture-navigation/GestureTarget';
export function SessionResultsPage({ sets, mode, status, elapsedMs, names, syncMessage, onProgress, onPlan, onRetry }: { sets: readonly SetCreate[]; mode: 'full' | 'quick-demo'; status: 'in_progress' | 'completed' | 'stopped'; elapsedMs: number; names: Readonly<Record<string, string>>; syncMessage: string; onProgress: () => void; onPlan: () => void; onRetry: () => void }) {
  const assessed = sets.filter(set => set.assessment_mode === 'camera').reduce((sum, set) => sum + set.total_reps, 0), accepted = sets.reduce((sum, set) => sum + set.accepted_reps, 0), manual = sets.filter(set => set.assessment_mode === 'manual' && set.completion_status === 'completed').length;
  return <section className="session-results" data-guide-target="results"><p className="dm-label">{mode === 'quick-demo' ? 'QUICK DEMO / ONE SET' : 'FULL WORKOUT / ACTUAL SETS'}</p><h1>{status === 'stopped' ? 'Тренировка остановлена' : 'Тренировка завершена'}</h1><p>Подходов: {sets.length} · Отмечено вручную: {manual} · Время с отдыхом: {Math.round(elapsedMs / 1000)} с</p>
    <p>Камера оценила {assessed} повторений. Корректных: {accepted}; с ошибками: {assessed - accepted}. {assessed ? `${Math.round(accepted / assessed * 100)}%` : 'Оценка камерой отсутствует'}.</p>
    {!sets.length && <p>Завершённых повторений нет. Пустая тренировка не отправляется в прогресс.</p>}
    <div className="session-set-list">{sets.map(set => <article className="dm-panel" key={set.client_set_id}><h3>{names[set.exercise_key] ?? set.exercise_key.replace(/_/g, ' ')} · подход {set.set_index}</h3><p>{set.assessment_mode === 'manual' ? 'Отмечено пользователем · камера не оценивала технику' : `Оценены камерой: ${set.total_reps} · корректные: ${set.accepted_reps}`} · {set.completion_status === 'partial' ? 'Неполный подход' : 'Завершён'}</p><p>Активное время: {Math.round(set.duration_ms / 1000)} с · Среднее время повторения: {set.metrics.mean_rep_duration_ms === null ? 'не измерено' : `${(set.metrics.mean_rep_duration_ms / 1000).toFixed(1)} с`}</p>
      {Object.keys(set.generic_error_counts ?? {}).length > 0 && <p>Подсказки техники: {Object.entries(set.generic_error_counts ?? {}).map(([code, count]) => `${code}: ${count}`).join(' · ')}</p>}
    </article>)}</div><p role="status">{syncMessage}</p><div className="dm-actions"><GestureTarget id="results-progress" onSelect={onProgress}>Открыть прогресс</GestureTarget><GestureTarget id="results-plan" onSelect={onPlan}>Вернуться к плану</GestureTarget><GestureTarget id="results-sync" onSelect={onRetry}>Повторить сохранение</GestureTarget></div></section>;
}
