export const gestureConfig = {
  roi: { minX: .15, maxX: .85, minY: .15, maxY: .85 },
  smoothingAlpha: .25,
  pinchEnterRatio: .32,
  pinchExitRatio: .45,
  pinchSamples: 3,
  minPalmWidth: .015,
  maxPalmWidth: .55,
  minimumClassificationConfidence: .65,
  holdMs: 600,
  releaseMs: 200,
  cooldownMs: 700,
  swipe: {
    smoothingAlpha: .7,
    minimumDistance: .16,
    maximumHorizontalDrift: .1,
    maximumStepDistance: .14,
    minimumDurationMs: 120,
    maximumDurationMs: 600,
    maximumGapMs: 250,
    minimumSamples: 3,
    settleDistance: .025,
    settleMs: 200,
    cooldownMs: 700,
  },
}
