export const gestureConfig = {
  roi: { minX: .15, maxX: .85, minY: .15, maxY: .85 },
  smoothingAlpha: .25,
  pinchEnterRatio: .32,
  pinchExitRatio: .45,
  pinchSamples: 3,
  minPalmWidth: .015,
  maxPalmWidth: .55,
  minimumClassificationConfidence: .65,
  holdMs: 600,
  releaseMs: 200,
  cooldownMs: 700,
  scroll: {
    smoothingAlpha: .7,
    extendedAngle: 155,
    curledAngle: 135,
    extendedReachRatio: 1.08,
    deadZone: .002,
    gain: 3,
    horizontalTolerance: .004,
    maximumHorizontalRatio: 1.3,
    maximumFingerDifference: .015,
    maximumStepDistance: .14,
    engageMs: 120,
    maximumGapMs: 250,
    minimumSamples: 3,
  },
}
